on:
  schedule:
    - cron: 0 4 * * *
name: Scheduled Test
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '14'
        check-latest: true
    - run: npm install
    - run: npm test
